name: rio_imaginario
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython=8.7.0
  - ipywidgets=8.1.1
  - matplotlib=3.6.2
  - numpy=1.23.5
  - openpyxl=3.1.2
  - pandas=2.2.1
  - pyDOE2=1.3.0
  - PyYAML=6.0
  - scipy=1.9.3
